version: '3.4'
services:
    frontend:
        build:
            context: .
            target: base
        container_name: react-weather
        image: react-weather
        command: npm start
        ports:
            - '5000:3000'
        volumes:
            - .:/app
            - /app/node_modules
