version: '3.4'
services:
    frontend:
        build:
            context: .
            target: base
        container_name: react-weather
        image: weather
        networks:
            - frontend
        command: npm start
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules

networks:
    frontend:
